version: 2
updates:

  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Europe/Rome
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
    labels:
      - dependencies
    groups:
      spring:
        patterns:
          - "org.springframework.boot:*"
          - "org.springframework.cloud:*"
      log4j:
        patterns:
          - "org.apache.logging.log4j:*"
      jna:
        patterns:
          - "net.java.dev.jna:*"
      feign:
        patterns:
          - "io.github.openfeign:*"
      smack:
        patterns:
          - "org.igniterealtime.smack:*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(ci)"
    labels:
      - ci