  version: '3'
  services:
    database:
      build:
       context: ./
       dockerfile: Dockerfile-ohdb
      image: oh-core_database:latest
      ports:
      - "3306:3306"
      command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --lower_case_table_names=1