FROM mariadb:10.6.11

ARG OH_DB_LANG=en

ENV MARIADB_DATABASE=oh
ENV MARIADB_ROOT_PASSWORD=root
ENV MARIADB_USER=isf
ENV MARIADB_PASSWORD=isf123

COPY sql/step_01_create_structure.sql /docker-entrypoint-initdb.d/
COPY sql/step_02_dump_menu.sql /docker-entrypoint-initdb.d/
COPY sql/step_03_dump_default_data_${OH_DB_LANG}.sql /docker-entrypoint-initdb.d/
#COPY sql/step_04_all_following_steps.sql /docker-entrypoint-initdb.d/
COPY sql/step_05_update_menu_i18n.sql /docker-entrypoint-initdb.d/
COPY sql/step_06_opd_extended.sql /docker-entrypoint-initdb.d/
COPY sql/step_07_modifiche_matiri.sql /docker-entrypoint-initdb.d/
COPY sql/step_08_int_restore_del_labrestype.sql /docker-entrypoint-initdb.d/
COPY sql/step_09_update_agetype.sql /docker-entrypoint-initdb.d/
COPY sql/step_1* /docker-entrypoint-initdb.d/
COPY sql/step_2* /docker-entrypoint-initdb.d/
COPY sql/step_3* /docker-entrypoint-initdb.d/
COPY sql/step_4* /docker-entrypoint-initdb.d/
COPY sql/step_5* /docker-entrypoint-initdb.d/
COPY sql/step_6* /docker-entrypoint-initdb.d/
COPY sql/step_7* /docker-entrypoint-initdb.d/
COPY sql/step_8* /docker-entrypoint-initdb.d/
COPY sql/step_9* /docker-entrypoint-initdb.d/
COPY sql/step_a1* /docker-entrypoint-initdb.d/
COPY sql/step_03_dump_vaccine_data_${OH_DB_LANG}.sql /docker-entrypoint-initdb.d/step_z100_dump_vaccine_data_${OH_DB_LANG}.sql
COPY sql/step_03_dump_dicomtype_data_${OH_DB_LANG}.sql /docker-entrypoint-initdb.d/step_z101_dump_dicomtype_data_${OH_DB_LANG}.sql
COPY sql/data_${OH_DB_LANG}/* data_${OH_DB_LANG}/
