version: '3'
services:
  database:
    build:
     context: ./
     dockerfile: Dockerfile-ohdb
     args:
       OH_DB_LANG: ${OH_DB_LANG}
    image: oh-core_database:latest
    ports:
    - "${OH_MARIADB_PORT}:3306"
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION" --lower_case_table_names=1 --explicit_defaults_for_timestamp=OFF
    environment:
      MARIADB_DATABASE: ${OH_MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${OH_MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${OH_MARIADB_USER}
      MARIADB_PASSWORD: ${OH_MARIADB_PASSWORD}
