CREATE TABLE PATIENT_PROFILE_PHOTO (
       PAT_ID int(11) NOT NULL,
       PAT_PHOTO BLOB,
       PRIMARY KEY (PAT_ID)
) ENGINE=MyISAM;

INSERT INTO PATIENT_PROFILE_PHOTO(PAT_ID, PAT_PHOTO)
    (SELECT p.PAT_ID, p.PAT_PHOTO
     FROM PATIENT p);