ALTER TABLE ADMISSION ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER ADM_DELETED,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE ADMISSIONTYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER ADMT_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE AGETYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER AT_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE BILLITEMS ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER BLI_QTY,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE BILLPAYMENTS ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER BLP_USR_ID_A,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE BILLS ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER BLL_USR_ID_A,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE DELIVERYRESULTTYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER DRT_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE DELIVERYTYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER DLT_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE DICOM ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER DM_THUMBNAIL,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE DISCHARGETYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER DIST_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE DISEASE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER DIS_IPD_OUT_INCLUDE,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE DISEASETYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL  AFTER DCL_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE EXAM ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER EXA_LOCK,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE EXAMROW ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER EXR_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE EXAMTYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER EXC_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE GROUPMENU ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER GM_ACTIVE,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE HOSPITAL ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER HOS_LOCK,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE LABORATORY ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL  AFTER LAB_PAT_INOUT,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE LABORATORYROW ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER LABR_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE MALNUTRITIONCONTROL ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MLN_LOCK,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE MEDICALDSR ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MDSR_LOCK,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE MEDICALDSRLOT ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER LT_LOCK,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE MEDICALDSRSTOCKMOV ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MMV_REFNO ,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE MEDICALDSRSTOCKMOVTYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MMVT_TYPE,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE MEDICALDSRSTOCKMOVWARD ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MMVN_MDSR_UNITS,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE MEDICALDSRTYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MDSRT_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE MEDICALDSRWARD ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MDSRWRD_OUT_QTI,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1;  
ALTER TABLE OPD ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER OPD_LOCK,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE OPERATION ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER OPE_LOCK,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE OPERATIONROW ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER OPER_TRANS_UNIT,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE OPERATIONTYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER OCL_TYPE,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE PATIENT ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER PAT_TIMESTAMP,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE PATIENTEXAMINATION ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER PEX_NOTE,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE PATIENTVACCINE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER PAV_LOCK,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE PREGNANTTREATMENTTYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER PTT_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE PRICELISTS ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER LST_CURRENCY,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE PRICES ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER PRC_PRICE,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE PRICESOTHERS ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER OTH_UNDEFINED,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1;  
ALTER TABLE SUPPLIER ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER SUP_DELETED,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE THERAPIES ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER THR_SMS,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE USER ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER US_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE USERGROUP ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER UG_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE VACCINE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER VAC_LOCK,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE VACCINETYPE ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER VACT_DESC,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1;  
ALTER TABLE VISITS ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER VST_SMS,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE WARD ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER WRD_LOCK,
  ADD COLUMN CREATED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE DATETIME NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 

