CREATE TABLE PERMISSIONS (
  P_ID_A int NOT NULL AUTO_INCREMENT,
  P_NAME varchar(50) NOT NULL default '',
  P_DESCRIPTION varchar(255) NOT NULL default '',
  P_ACTIVE char(1) NOT NULL default '',
  P_CREATED_BY varchar(50) default NULL,
  P_CREATED_DATE datetime default NULL,
  P_LAST_MODIFIED_BY varchar(50) default NULL,
  P_LAST_MODIFIED_DATE datetime default NULL,
  PRIMARY KEY (P_ID_A)
) ENGINE=MyISAM;

INSERT INTO PERMISSIONS VALUES ('opd.read','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('opd.create','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('opd.update','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('opd.delete','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('summary.read','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('summary.create','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('summary.update','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('summary.delete','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('examination.read','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('examination.create','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('examination.update','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('examination.delete','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('admission.read','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('admission.create','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('admission.update','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('admission.delete','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('therapy.read','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('therapy.create','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('therapy.update','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('therapy.delete','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('vaccine.read','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('vaccine.create','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('vaccine.update','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('vaccine.delete','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('exam.read','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('exam.create','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('exam.update','',1,NULL,NULL,NULL,NULL);
INSERT INTO PERMISSIONS VALUES ('exam.delete','',1,NULL,NULL,NULL,NULL);

CREATE TABLE GROUPPERMISSION (
  GP_ID int NOT NULL AUTO_INCREMENT,
  GP_UG_ID_A varchar(50) NOT NULL default '',
  GP_P_ID_A int NOT NULL,
  GP_ACTIVE char(1) NOT NULL default '',
  GP_CREATED_BY varchar(50) default NULL,
  GP_CREATED_DATE datetime default NULL,
  GP_LAST_MODIFIED_BY varchar(50) default NULL,
  GP_LAST_MODIFIED_DATE datetime default NULL,
  PRIMARY KEY (GP_ID)
) ENGINE=MyISAM;

INSERT INTO GROUPPERMISSION VALUES ('admin',1,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',2,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',3,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',4,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',5,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',6,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',7,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',8,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',9,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',10,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',11,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',12,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',13,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',14,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',15,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',16,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',17,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',18,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',19,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',20,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',21,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',22,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',23,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',24,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',25,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',26,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',27,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('admin',28,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('guest',1,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('guest',5,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('guest',9,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('guest',13,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('guest',17,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('guest',21,1,NULL,NULL,NULL,NULL);
INSERT INTO GROUPPERMISSION VALUES ('guest',25,1,NULL,NULL,NULL,NULL);