#ALTER TABLE oh.admission ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
#  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
#  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
#  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
#  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.admissiontype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.agetype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.billitems ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.billpayments ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.bills ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.deliveryresulttype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.deliverytype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.dicom ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.dischargetype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.disease ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.diseasetype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.exam ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.examrow ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.examtype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.groupmenu ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.hospital ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.laboratory ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.laboratoryrow ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.malnutritioncontrol ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsr ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrlot ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrstockmov ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrstockmovtype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrstockmovward ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrtype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrward ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.menuitem ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.opd ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.operation ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.operationrow ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.operationtype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.patient ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.patientexamination ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.patientvaccine ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.pregnanttreatmenttype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.pricelists ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.prices ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.pricesothers ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1;  
ALTER TABLE oh.supplier ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.therapies ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.user ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.usergroup ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.vaccine ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.vaccinetype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1;  
ALTER TABLE oh.visits ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 
ALTER TABLE oh.ward ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,\
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,\
  ADD COLUMN ACTIVE int NOT NULL DEFAULT 1; 


