ALTER TABLE PATIENTEXAMINATION 
CHANGE COLUMN PEX_HEIGHT PEX_HEIGHT DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN PEX_WEIGHT PEX_WEIGHT INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN PEX_PA_MIN PEX_PA_MIN INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN PEX_PA_MAX PEX_PA_MAX INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN PEX_FC PEX_HR INT(11) NULL DEFAULT NULL ,
CHANGE COLUMN PEX_TEMP PEX_TEMP DOUBLE NULL DEFAULT NULL ,
CHANGE COLUMN PEX_SAT PEX_SAT DOUBLE NULL DEFAULT NULL ;

UPDATE patientexamination SET PEX_HEIGHT = NULL WHERE PEX_HEIGHT = 0;
UPDATE patientexamination SET PEX_WEIGHT = NULL WHERE PEX_WEIGHT = 0;
UPDATE patientexamination SET PEX_PA_MIN = NULL WHERE PEX_PA_MIN = 0;
UPDATE patientexamination SET PEX_PA_MAX = NULL WHERE PEX_PA_MAX = 0;
UPDATE patientexamination SET PEX_HR = NULL WHERE PEX_HR = 0;
UPDATE patientexamination SET PEX_TEMP = NULL WHERE PEX_TEMP = 0;
UPDATE patientexamination SET PEX_SAT = NULL WHERE PEX_SAT = 0;
UPDATE patientexamination SET PEX_NOTE = NULL WHERE PEX_NOTE = '';