ALTER TABLE oh.admission ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER ADM_DELETED,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.admissiontype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER ADMT_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.agetype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER AT_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.billitems ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER BLI_QTY,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.billpayments ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER BLP_USR_ID_A,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.bills ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER BLL_USR_ID_A,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.deliveryresulttype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER DRT_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.deliverytype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER DLT_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.dicom ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER DM_THUMBNAIL,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.dischargetype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER DIST_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.disease ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER DIS_IPD_OUT_INCLUDE,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.diseasetype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL  AFTER DCL_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.exam ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER EXA_LOCK,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.examrow ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER EXR_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.examtype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER EXC_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.groupmenu ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER GM_ACTIVE,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.hospital ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER HOS_LOCK,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.laboratory ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL  AFTER LAB_PAT_INOUT,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.laboratoryrow ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER LABR_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.malnutritioncontrol ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MLN_LOCK,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsr ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MDSR_LOCK,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrlot ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER LT_LOCK,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrstockmov ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MMV_REFNO ,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrstockmovtype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MMVT_TYPE,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrstockmovward ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MMVN_MDSR_UNITS,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrtype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MDSRT_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.medicaldsrward ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER MDSRWRD_OUT_QTI,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1;  
ALTER TABLE oh.opd ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER OPD_LOCK,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.operation ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER OPE_LOCK,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.operationrow ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER OPER_TRANS_UNIT,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.operationtype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER OCL_TYPE,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.patient ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER PAT_TIMESTAMP,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.patientexamination ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER PEX_NOTE,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.patientvaccine ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER PAV_LOCK,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.pregnanttreatmenttype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER PTT_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.pricelists ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER LST_CURRENCY,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.prices ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER PRC_PRICE,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.pricesothers ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER OTH_UNDEFINED,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1;  
ALTER TABLE oh.supplier ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER SUP_DELETED,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.therapies ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER THR_SMS,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.user ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER US_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.usergroup ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER UG_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.vaccine ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER VAC_LOCK,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.vaccinetype ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER VACT_DESC,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1;  
ALTER TABLE oh.visits ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER VST_SMS,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 
ALTER TABLE oh.ward ADD COLUMN CREATED_BY VARCHAR(50) NULL DEFAULT NULL AFTER WRD_LOCK,
  ADD COLUMN CREATED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
  ADD COLUMN LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
  ADD COLUMN ACTIVE TINYINT(1) NOT NULL DEFAULT 1; 

