CREATE TABLE PERMISSIONS (
  	P_ID_A int NOT NULL AUTO_INCREMENT,
  	P_NAME varchar(50)  NOT NULL,
  	P_DESCRIPTION varchar(255)  NOT NULL,
  	P_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
   	P_CREATED_BY VARCHAR(50) NULL DEFAULT NULL, 
  	P_CREATED_DATE datetime NULL DEFAULT NULL, 
  	P_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL, 
  	P_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL, 
  	PRIMARY KEY (P_ID_A)
) ENGINE=MyISAM;
