CREATE TABLE GROUPPERMISSION (
  	GP_ID int NOT NULL AUTO_INCREMENT,
  	GP_UG_ID_A varchar(50) NOT NULL DEFAULT '',
  	GP_P_ID_A int NOT NULL,
  	GP_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  	GP_CREATED_BY VARCHAR(50) NULL DEFAULT NULL, 
  	GP_CREATED_DATE datetime NULL DEFAULT NULL, 
  	GP_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL, 
  	GP_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL, 
  	PRIMARY KEY (GP_ID),
  	FOREIGN KEY (GP_UG_ID_A) REFERENCES USERGROUP(UG_ID_A),
  	FOREIGN KEY (GP_P_ID_A) REFERENCES PERMISSIONS(P_ID_A_ID)
) ENGINE=MyISAM;
