ALTER TABLE `MEDICALDSRWARD` 
ADD COLUMN `MDSRWRD_LT_ID_A` VARCHAR(50) NULL AFTER `MDSRWRD_OUT_QTI`,
ADD INDEX `FK_LOT` (`MDSRWRD_LT_ID_A` ASC);
ALTER TABLE `MEDICALDSRWARD` 
ADD CONSTRAINT `FK_MEDICALDSRWARD_MEDICALDSRLOT`
  FOREIGN KEY (`MDSRWRD_LT_ID_A`)
  REFERENCES `MEDICALDSRLOT` (`LT_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `MEDICALDSRSTOCKMOVWARD` 
ADD COLUMN `MMVN_LT_ID` VARCHAR(50) NULL AFTER `MMVN_WRD_ID_A_TO`,
ADD INDEX `FK_FK_MEDICALDSRSTOCKMOVWARD_LOT` (`MMVN_LT_ID` ASC);
ALTER TABLE `MEDICALDSRSTOCKMOVWARD` 
ADD CONSTRAINT `FK_MEDICALDSRSTOCKMOVWARD_LOT`
  FOREIGN KEY (`MMVN_LT_ID`)
  REFERENCES `MEDICALDSRLOT` (`LT_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  
  
  ALTER TABLE `MEDICALDSRLOT` 
ADD COLUMN `LT_MDSR_ID` INT(11) NULL AFTER `LT_ACTIVE`;
ALTER TABLE `MEDICALDSRLOT` 
ADD INDEX `FK_MEDICALDSRLOT_MEDICALDSE_idx` (`LT_MDSR_ID` ASC);
ALTER TABLE `MEDICALDSRLOT` 
ADD CONSTRAINT `FK_MEDICALDSRLOT_MEDICALDSE`
  FOREIGN KEY (`LT_MDSR_ID`)
  REFERENCES `MEDICALDSR` (`MDSR_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

UPDATE `MEDICALDSRLOT` 
       JOIN `MEDICALDSRSTOCKMOV` 
       ON MEDICALDSRLOT.LT_ID_A = MEDICALDSRSTOCKMOV.MMV_LT_ID_A
SET    MEDICALDSRLOT.LT_MDSR_ID =MEDICALDSRSTOCKMOV.MMV_MDSR_ID
