-- changing date type from VARCHAR to DATETIME to ease sorting
ALTER TABLE DICOM
CHANGE COLUMN DM_FILE_ST_DATE DM_FILE_ST_DATE DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN DM_FILE_SER_DATE DM_FILE_SER_DATE DATETIME NULL DEFAULT NULL ;

