-- "admin" user
INSERT INTO OH_GROUPPERMISSION (GP_UG_ID_A, GP_P_ID_A, GP_ACTIVE, GP_CREATED_BY, GP_CREATED_DATE, GP_LAST_MODIFIED_BY, GP_LAST_MODIFIED_DATE) VALUES ('admin',140,1,NULL,NULL,NULL,NULL);
