/* INCOMPATIBLE TYPES
ALTER TABLE `oh_billitems` 
ADD INDEX `FK_BILLITEMS_PRICE_IDX` (`BLI_ID_PRICE` ASC) VISIBLE;
;
ALTER TABLE `oh_billitems` 
ADD CONSTRAINT `FK_BILLITEMS_PRICE`
  FOREIGN KEY (`BLI_ID_PRICE`)
  REFERENCES `oh_prices` (`PRC_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
*/
  
ALTER TABLE `oh_dicom` 
ADD INDEX `FK_DICOM_PATIENT_IDX` (`DM_PAT_ID` ASC) VISIBLE;
;
ALTER TABLE `oh_dicom` 
ADD CONSTRAINT `FK_DICOM_PATIENT`
  FOREIGN KEY (`DM_PAT_ID`)
  REFERENCES `oh_patient` (`PAT_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE `oh_groupmenu` 
ADD INDEX `FK_GROUPMENU_MENUITEM_IDX` (`GM_MNI_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_groupmenu` 
ADD CONSTRAINT `FK_GROUPMENU_MENUITEM`
  FOREIGN KEY (`GM_MNI_ID_A`)
  REFERENCES `oh_menuitem` (`MNI_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_groupmenu` 
ADD INDEX `FK_GROUPMENU_USERGROUP_IDX` (`GM_UG_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_groupmenu` 
ADD CONSTRAINT `FK_GROUPMENU_USERGROUP`
  FOREIGN KEY (`GM_UG_ID_A`)
  REFERENCES `oh_usergroup` (`UG_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `oh_grouppermission` 
ADD INDEX `FK_GROUPPERMISSION_PERMISSIONS_IDX` (`GP_P_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_grouppermission` 
ADD CONSTRAINT `FK_GROUPPERMISSION_PERMISSIONS`
  FOREIGN KEY (`GP_P_ID_A`)
  REFERENCES `oh_permissions` (`P_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE `oh_grouppermission` 
ADD INDEX `FK_GROUPPERMISSION_USERGROUP_IDX` (`GP_UG_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_grouppermission` 
ADD CONSTRAINT `FK_GROUPPERMISSION_USERGROUP`
  FOREIGN KEY (`GP_UG_ID_A`)
  REFERENCES `oh_usergroup` (`UG_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_malnutritioncontrol` 
ADD INDEX `FK_MALNUTRITIONCONTROL_ADMISSION_IDX` (`MLN_ADM_ID` ASC) VISIBLE;
;
ALTER TABLE `oh_malnutritioncontrol` 
ADD CONSTRAINT `FK_MALNUTRITIONCONTROL_ADMISSION`
  FOREIGN KEY (`MLN_ADM_ID`)
  REFERENCES `oh_admission` (`ADM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_operationrow` 
ADD INDEX `FK_OPERATIONROW_ADMISSION_IDX` (`OPER_ADMISSION_ID` ASC) VISIBLE;
;
ALTER TABLE `oh_operationrow` 
ADD CONSTRAINT `FK_OPERATIONROW_ADMISSION`
  FOREIGN KEY (`OPER_ADMISSION_ID`)
  REFERENCES `oh_admission` (`ADM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_operationrow` 
ADD INDEX `FK_OPERATIONROW_BILLS_IDX` (`OPER_BILL_ID` ASC) VISIBLE;
;
ALTER TABLE `oh_operationrow` 
ADD CONSTRAINT `FK_OPERATIONROW_BILLS`
  FOREIGN KEY (`OPER_BILL_ID`)
  REFERENCES `oh_bills` (`BLL_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_operationrow` 
ADD INDEX `FK_OPERATIONROW_OPD_IDX` (`OPER_OPD_ID` ASC) VISIBLE;
;
ALTER TABLE `oh_operationrow` 
ADD CONSTRAINT `FK_OPERATIONROW_OPD`
  FOREIGN KEY (`OPER_OPD_ID`)
  REFERENCES `oh_opd` (`OPD_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_medicaldsrstockmov` 
ADD INDEX `FK_MEDICALDSRSTOCKMOV_MEDICALDSRLOT_IDX` (`MMV_LT_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_medicaldsrstockmov` 
ADD CONSTRAINT `FK_MEDICALDSRSTOCKMOV_MEDICALDSRLOT`
  FOREIGN KEY (`MMV_LT_ID_A`)
  REFERENCES `oh_medicaldsrlot` (`LT_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

/* INCOMPATIBLE TYPES
ALTER TABLE `oh_medicaldsrstockmovward` 
ADD INDEX `FK_MEDICALDSRSTOCKMOVWARD_MEDICALDSR_IDX` (`MMVN_MDSR_ID` ASC) VISIBLE;
;
ALTER TABLE `oh_medicaldsrstockmovward` 
ADD CONSTRAINT `FK_MEDICALDSRSTOCKMOVWARD_MEDICALDSR`
  FOREIGN KEY (`MMVN_MDSR_ID`)
  REFERENCES `oh_medicaldsr` (`MDSR_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
*/
  
ALTER TABLE `oh_medicaldsrstockmovward` 
ADD INDEX `FK_MEDICALDSRSTOCKMOVWARD_WARD_FROM_IDX` (`MMVN_WRD_ID_A_FROM` ASC) VISIBLE;
;
ALTER TABLE `oh_medicaldsrstockmovward` 
ADD CONSTRAINT `FK_MEDICALDSRSTOCKMOVWARD_WARD_FROM`
  FOREIGN KEY (`MMVN_WRD_ID_A_FROM`)
  REFERENCES `oh_ward` (`WRD_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_medicaldsrstockmovward` 
ADD INDEX `FK_MEDICALDSRSTOCKMOVWARD_WARD_TO_IDX` (`MMVN_WRD_ID_A_TO` ASC) VISIBLE;
;
ALTER TABLE `oh_medicaldsrstockmovward` 
ADD CONSTRAINT `FK_MEDICALDSRSTOCKMOVWARD_WARD_TO`
  FOREIGN KEY (`MMVN_WRD_ID_A_TO`)
  REFERENCES `oh_ward` (`WRD_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;