-- extend WRD_ID_A to CHAR(3) and update all its references
-- drop foreign keys and indexes
ALTER TABLE OH_ADMISSION DROP FOREIGN KEY FK_ADMISSION_WARD;
ALTER TABLE OH_ADMISSION DROP INDEX FK_ADMISSION_WARD;
ALTER TABLE OH_MEDICALDSRSTOCKMOV DROP FOREIGN KEY FK_MEDICALDSRSTOCKMOV_WARD;
ALTER TABLE OH_MEDICALDSRSTOCKMOV DROP INDEX FK_MEDICALDSRSTOCKMOV_WARD;
ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD DROP FOREIGN KEY FK_MEDICALDSRSTOCKMOVWARD_WARD;
ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD DROP INDEX FK_MEDICALDSRSTOCKMOVWARD_WARD_idx;
ALTER TABLE OH_MEDICALDSRWARD DROP FOREIGN KEY FK_MEDICALDSRWARD_WARD;
ALTER TABLE OH_MEDICALDSRWARD DROP INDEX FK_MEDICALDSRWARD_WARD_idx;
ALTER TABLE OH_VISITS DROP FOREIGN KEY FK_VISITS_WARD;
ALTER TABLE OH_VISITS DROP INDEX FK_VISITS_WARD;

-- change columns types
ALTER TABLE OH_WARD MODIFY COLUMN WRD_ID_A CHAR(3) NOT NULL DEFAULT '' ;
ALTER TABLE OH_ADMISSION MODIFY COLUMN ADM_WRD_ID_A CHAR(3) NOT NULL DEFAULT '' ;
ALTER TABLE OH_MEDICALDSRWARD MODIFY COLUMN MDSRWRD_WRD_ID_A CHAR(3) NOT NULL DEFAULT '';
ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD MODIFY COLUMN MMVN_WRD_ID_A CHAR(3) NOT NULL DEFAULT '';
ALTER TABLE OH_MEDICALDSRSTOCKMOV MODIFY COLUMN MMV_WRD_ID_A CHAR(3) DEFAULT '';
ALTER TABLE OH_VISITS MODIFY COLUMN VST_WRD_ID_A CHAR(3) DEFAULT '';

-- add again foreign keys and indexes
ALTER TABLE OH_ADMISSION
	ADD CONSTRAINT FK_ADMISSION_WARD
	    FOREIGN KEY (ADM_WRD_ID_A )
	    REFERENCES OH_WARD (WRD_ID_A )
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	ADD INDEX FK_ADMISSION_WARD_idx (ADM_WRD_ID_A ASC);

ALTER TABLE OH_MEDICALDSRSTOCKMOV
 	ADD CONSTRAINT FK_MEDICALDSRSTOCKMOV_WARD
	    FOREIGN KEY (MMV_WRD_ID_A )
	    REFERENCES OH_WARD (WRD_ID_A )
	    ON DELETE NO ACTION
    	ON UPDATE NO ACTION,
	ADD INDEX FK_MEDICALDSRSTOCKMOV_WARD_idx (MMV_WRD_ID_A ASC);

ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD  	
    ADD CONSTRAINT FK_MEDICALDSRSTOCKMOVWARD_WARD
	    FOREIGN KEY (MMVN_WRD_ID_A )
	    REFERENCES OH_WARD (WRD_ID_A )
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	ADD INDEX FK_MEDICALDSRSTOCKMOVWARD_WARD_idx (MMVN_WRD_ID_A ASC);

ALTER TABLE OH_MEDICALDSRWARD  	    
 	ADD CONSTRAINT FK_MEDICALDSRWARD_WARD
	    FOREIGN KEY (MDSRWRD_WRD_ID_A )
	    REFERENCES OH_WARD (WRD_ID_A )
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	ADD INDEX FK_MEDICALDSRWARD_WARD_idx (MDSRWRD_WRD_ID_A ASC);
        
ALTER TABLE OH_VISITS
	ADD CONSTRAINT FK_VISITS_WARD 
		FOREIGN KEY (VST_WRD_ID_A) 
        REFERENCES OH_WARD (WRD_ID_A) 
        ON DELETE NO ACTION 
        ON UPDATE NO ACTION,
	ADD INDEX FK_VISITS_WARD_idx (VST_WRD_ID_A ASC);
	
-- add new field to WARD table
ALTER TABLE OH_WARD ADD COLUMN WRD_IS_OPD TINYINT(1) NOT NULL DEFAULT '0' AFTER WRD_NDOC;
INSERT INTO OH_WARD (WRD_ID_A, WRD_NAME, WRD_TELE, WRD_FAX, WRD_EMAIL, WRD_NBEDS, WRD_NQUA_NURS, WRD_NDOC, WRD_IS_OPD, WRD_IS_PHARMACY, WRD_IS_MALE, WRD_IS_FEMALE, WRD_VISIT_DURATION, WRD_LOCK, WRD_CREATED_BY, WRD_CREATED_DATE, WRD_ACTIVE) 
VALUES ('OPD', 'OPD', 212, '', '', '0', '1', '1', '1', '1', '1', '1', '15', '0', 'admin', NOW(), '1');

-- add new field to OPD table
ALTER TABLE OH_OPD ADD COLUMN OPD_WRD_ID_A CHAR(3) NULL DEFAULT NULL AFTER OPD_ID;
UPDATE OH_OPD SET OPD_WRD_ID_A = 'OPD'; -- set new 'OPD' ward for previous data
ALTER TABLE OH_OPD ADD INDEX FK_OPD_WARD_idx (OPD_WRD_ID_A ASC); -- add index
ALTER TABLE OH_OPD CHANGE COLUMN OPD_WRD_ID_A OPD_WRD_ID_A CHAR(3) NOT NULL ; -- set not null
ALTER TABLE OH_OPD 
ADD CONSTRAINT FK_OPD_WARD
  FOREIGN KEY (OPD_WRD_ID_A)
  REFERENCES OH_WARD (WRD_ID_A)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION; -- add foreign key
  
-- update VISITS table
UPDATE OH_VISITS SET VST_WRD_ID_A = 'OPD', VST_DURATION = 15, VST_SERVICE = '' WHERE VST_WRD_ID_A IS NULL; -- set new 'OPD' ward for previous data

-- convert OPD_DATE_NEXT_VIS into FK
ALTER TABLE OH_OPD ADD OPD_NEXT_VISIT_ID INT(11) NULL AFTER OPD_USR_ID_A; -- the new field

-- update new fields
UPDATE OH_OPD SET OPD_NEXT_VISIT_ID = (SELECT VST_ID FROM OH_VISITS WHERE VST_WRD_ID_A = 'OPD' AND VST_PAT_ID = OPD_PAT_ID AND VST_DATE = OPD_DATE_NEXT_VIS);

-- add indexes foreign keys
ALTER TABLE OH_OPD 
ADD INDEX FK_OPD_NEXT_VISIT_idx (OPD_NEXT_VISIT_ID ASC);
ALTER TABLE OH_OPD 
ADD CONSTRAINT FK_OPD_NEXT_VISIT
  FOREIGN KEY (OPD_NEXT_VISIT_ID)
  REFERENCES OH_VISITS (VST_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
-- drop OPD_DATE_NEXT_VIS field
ALTER TABLE OH_OPD DROP COLUMN OPD_DATE_NEXT_VIS;