-- Step 1: Drop the foreign key constraint
ALTER TABLE OH_MEDICALDSRINVENTORY 
DROP CONSTRAINT oh_medicaldsrinventory_ibfk_2;

ALTER TABLE OH_MEDICALDSRINVENTORY 
DROP CONSTRAINT oh_medicaldsrinventory_ibfk_1;

ALTER TABLE OH_MEDICALDSRINVENTORY 
DROP CONSTRAINT oh_medicaldsrinventory_ibfk_3;

ALTER TABLE OH_MEDICALDSRINVENTORY 
DROP CONSTRAINT oh_medicaldsrinventory_ibfk_4;

ALTER TABLE OH_MEDICALDSRINVENTORY 
DROP CONSTRAINT oh_medicaldsrinventory_ibfk_5;

ALTER TABLE OH_MEDICALDSRINVENTORY 
DROP CONSTRAINT oh_medicaldsrinventory_ibfk_6;

-- Step 2: Change the data type of the foreign key column
ALTER TABLE OH_MEDICALDSRINVENTORY 
MODIFY COLUMN MINVT_WRD_ID_A CHAR(3);

-- Step 3: Recreate the foreign key constraint
ALTER TABLE OH_MEDICALDSRINVENTORY 
ADD CONSTRAINT FK_MEDICALDSRINVENTORY_WARD_1
FOREIGN KEY (MINVT_WRD_ID_A) REFERENCES OH_WARD (WRD_ID_A);

ALTER TABLE OH_MEDICALDSRINVENTORY 
ADD CONSTRAINT FK_MEDICALDSRINVENTORY_USER
FOREIGN KEY (MINVT_US_ID_A) REFERENCES OH_USER (US_ID_A);

ALTER TABLE OH_MEDICALDSRINVENTORY 
ADD CONSTRAINT FK_MEDICALDSRINVENTORY_MEDICALDSRSTOCKMOVTYPE_1
FOREIGN KEY (MINVT_CHARGE_TYPE) REFERENCES OH_MEDICALDSRSTOCKMOVTYPE (MMVT_ID_A);

ALTER TABLE OH_MEDICALDSRINVENTORY 
ADD CONSTRAINT FK_MEDICALDSRINVENTORY_MEDICALDSRSTOCKMOVTYPE_2
FOREIGN KEY (MINVT_DISCHARGE_TYPE) REFERENCES OH_MEDICALDSRSTOCKMOVTYPE (MMVT_ID_A);

ALTER TABLE OH_MEDICALDSRINVENTORY 
ADD CONSTRAINT FK_MEDICALDSRINVENTORY_SUPPLIER
FOREIGN KEY (MINVT_SUPPLIER) REFERENCES OH_SUPPLIER (SUP_ID);

ALTER TABLE OH_MEDICALDSRINVENTORY 
ADD CONSTRAINT FK_MEDICALDSRINVENTORY_WARD_2
FOREIGN KEY (MINVT_DESTINATION) REFERENCES OH_WARD (WRD_ID_A);



