ALTER TABLE OH_MEDICALDSRLOT ADD COLUMN LT_QTY DECIMAL(19,2) NOT NULL DEFAULT 0 AFTER LT_COST;

UPDATE OH_MEDICALDSRLOT SET LT_QTY =
	COALESCE((SELECT SUM(CASE WHEN MMVT_TYPE LIKE '+%' THEN MMV_QTY ELSE -MMV_QTY END)
		FROM OH_MEDICALDSRSTOCKMOV JOIN OH_MEDICALDSRSTOCKMOVTYPE ON MMV_MMVT_ID_A = MMVT_ID_A
		WHERE MMV_LT_ID_A = LT_ID_A), 0)
	+ COALESCE((SELECT SUM(MDSRWRD_IN_QTI - MDSRWRD_OUT_QTI)
		FROM OH_MEDICALDSRWARD
		WHERE MDSRWRD_LT_ID_A = LT_ID_A), 0);
