CREATE TABLE OH_SESSION_AUDIT (
  SEA_ID INT(11) NOT NULL AUTO_INCREMENT,
  SEA_US_ID_A VARCHAR(50) NOT NULL,
  SEA_LOGIN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SEA_LOGOUT TIMESTAMP NULL,
  PRIMARY KEY (SES_ID),
  FOREIGN KEY (SEA_US_ID_A) REFERENCES OH_USER(US_ID_A)
);