-- Add pre admission treatment and assessment columns
ALTER TABLE OH_ADMISSION
    ADD COLUMN ADM_PRE_TREATMENT TEXT DEFAULT NULL,
    ADD COLUMN ADM_PRE_ASSESSMENT TEXT DEFAULT NULL,
    ADD COLUMN ADM_ENTRY_REASON TEXT DEFAULT NULL,
    CHANGE ADM_NOTE ADM_ANAMNESIS TEXT DEFAULT NULL;