ALTER TABLE oh_admission ADD COLUMN ADM_ENTRY_REASON TEXT DEFAULT NULL;
ALTER TABLE oh_admission DROP COLUMN ADM_CONDITION_AT_ADMISSION;
ALTER TABLE oh_admission CHANGE ADM_NOTE ADM_ANAMNESIS TEXT DEFAULT NULL;