--
-- Add lock (version) column in tables where it's missing
--

ALTER TABLE OH_BILLS
    ADD COLUMN BLL_LOCK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE OH_AGETYPE
    ADD COLUMN AT_LOCK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE OH_PATIENTHISTORY
    ADD COLUMN PAH_LOCK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE OH_PATIENTEXAMINATION
    ADD COLUMN PEX_LOCK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE OH_USER_SETTINGS
    ADD COLUMN USS_LOCK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE OH_PRICES
    ADD COLUMN PRC_LOCK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE OH_PRICELISTS
    ADD COLUMN LST_LOCK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE OH_SUPPLIER
    ADD COLUMN SUP_LOCK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE OH_PRICESOTHERS
    ADD COLUMN OTH_LOCK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE OH_VISITS
    ADD COLUMN VST_LOCK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE OH_MEDICALDSRWARD
    ADD COLUMN MDSRWRD_LOCK INT(11) NOT NULL DEFAULT 0;