ALTER TABLE OH_OPERATION MODIFY COLUMN OPE_FOR VARCHAR(20);

UPDATE OH_OPERATION
    SET OPE_FOR='OPD_ADMISSION' WHERE OPE_FOR='1';
UPDATE OH_OPERATION
    SET OPE_FOR='ADMISSION' WHERE OPE_FOR='2';
UPDATE OH_OPERATION
    SET OPE_FOR='OPD' WHERE OPE_FOR='3';

ALTER TABLE OH_OPERATION
    MODIFY COLUMN OPE_FOR ENUM('OPD', 'ADMISSION', 'OPD_ADMISSION') DEFAULT 'OPD_ADMISSION';