-- OP-1021: DRAFT movements in Pharmaceutical Stock.
-- A draft is persisted wizard state (header + rows as typed, possibly incomplete):
-- it never touches stock quantities and is deleted once the movement is confirmed
-- through the standard insertion path.

CREATE TABLE OH_MEDICALDSRSTOCKMOVDRAFT (
	MMVD_ID int NOT NULL AUTO_INCREMENT,
	MMVD_KIND varchar(10) NOT NULL,
	MMVD_MMVT_ID_A varchar(10) NULL,
	MMVD_DATE datetime NULL,
	MMVD_REFNO varchar(50) NULL,
	MMVD_SUP_ID int NULL,
	MMVD_WRD_ID_A char(3) NULL,
	MMVD_LOCK int NOT NULL default 0,
	MMVD_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
	MMVD_CREATED_DATE datetime NULL DEFAULT NULL,
	MMVD_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
	MMVD_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
	MMVD_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (MMVD_ID),
	FOREIGN KEY (MMVD_MMVT_ID_A) REFERENCES OH_MEDICALDSRSTOCKMOVTYPE (MMVT_ID_A),
	FOREIGN KEY (MMVD_SUP_ID) REFERENCES OH_SUPPLIER (SUP_ID),
	FOREIGN KEY (MMVD_WRD_ID_A) REFERENCES OH_WARD (WRD_ID_A)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;

-- The lot is stored denormalized (code as typed + dates + cost + new-lot flag) and deliberately
-- without a foreign key: a draft row may reference a lot that does not exist yet.
CREATE TABLE OH_MEDICALDSRSTOCKMOVDRAFTROW (
	MMVDR_ID int NOT NULL AUTO_INCREMENT,
	MMVDR_MMVD_ID int NOT NULL,
	MMVDR_MDSR_ID int NOT NULL,
	MMVDR_QTY int NOT NULL default 0,
	MMVDR_UNITS_OR_PACKETS TINYINT(1) NOT NULL DEFAULT 0,
	MMVDR_LT_ID_A varchar(50) NULL,
	MMVDR_LT_PREP_DATE datetime NULL,
	MMVDR_LT_DUE_DATE datetime NULL,
	MMVDR_LT_COST double NULL,
	MMVDR_IS_NEW_LOT TINYINT(1) NOT NULL DEFAULT 0,
	MMVDR_UPDATE_LOT_COST TINYINT(1) NOT NULL DEFAULT 0,
	MMVDR_LOCK int NOT NULL default 0,
	MMVDR_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
	MMVDR_CREATED_DATE datetime NULL DEFAULT NULL,
	MMVDR_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
	MMVDR_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
	MMVDR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (MMVDR_ID),
	FOREIGN KEY (MMVDR_MMVD_ID) REFERENCES OH_MEDICALDSRSTOCKMOVDRAFT (MMVD_ID),
	FOREIGN KEY (MMVDR_MDSR_ID) REFERENCES OH_MEDICALDSR (MDSR_ID)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;
