CREATE TABLE OH_CARES (
    CR_ID INT AUTO_INCREMENT PRIMARY KEY,
    CR_PAT_ID INT NOT NULL,
    CR_TEAM LONGTEXT NULL,
    CR_CARE_DATE LONGTEXT NULL,
    CR_PLANNED_CARE LONGTEXT NULL,
    CR_OBSERVATION LONGTEXT NULL,
    CR_NOTE LONGTEXT NULL,
    CR_PERFORMED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CR_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CR_LOCK INT(11) NOT NULL DEFAULT 0,
    CR_CREATED_BY VARCHAR(100),
    CR_CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CR_LAST_MODIFIED_BY VARCHAR(100),
    CR_LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_CR_PATIENT FOREIGN KEY(CR_PAT_ID) REFERENCES OH_PATIENT(PAT_ID)
);