ALTER TABLE HOSPITAL ADD COLUMN HOS_VISIT_START time NOT NULL DEFAULT '06:30:00' AFTER HOS_CURR_COD;
ALTER TABLE HOSPITAL ADD COLUMN HOS_VISIT_END time NOT NULL DEFAULT '20:00:00' AFTER HOS_VISIT_START;
ALTER TABLE HOSPITAL ADD COLUMN HOS_VISIT_INCREMENT int(11) NOT NULL DEFAULT 15 AFTER HOS_VISIT_END;
ALTER TABLE HOSPITAL ADD COLUMN HOS_VISIT_DURATION int(11) NOT NULL DEFAULT 30 AFTER HOS_VISIT_INCREMENT;