ALTER TABLE OH_PATIENT
ADD COLUMN PAT_COMMUNE VARCHAR(50) DEFAULT NULL,
ADD COLUMN PAT_ETHNIC VARCHAR(50) DEFAULT NULL,
ADD COLUMN PAT_FATHER_OCCUPATION VARCHAR(50) NULL,
ADD COLUMN PAT_FATHER_AGE int(11) DEFAULT NULL ,
ADD COLUMN PAT_FATHER_PHONE VARCHAR(50) NULL,
ADD COLUMN PAT_MOTHER_OCCUPATION VARCHAR(50) NULL,
ADD COLUMN PAT_MOTHER_AGE int NOT NULL ,
ADD COLUMN PAT_MOTHER_PHONE VARCHAR(50) NULL;