-- alter table oh_dicomtype --------------

ALTER TABLE OH_DICOMTYPE 
ADD COLUMN DCMT_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
ADD COLUMN DCMT_CREATED_DATE datetime NULL DEFAULT NULL,
ADD COLUMN DCMT_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
ADD COLUMN DCMT_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
ADD COLUMN DCMT_ACTIVE TINYINT(1) NOT NULL DEFAULT 1;

-- alter table oh_dicom_data --------------

ALTER TABLE OH_DICOM_DATA
ADD COLUMN DMD_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
ADD COLUMN DMD_CREATED_DATE datetime NULL DEFAULT NULL,
ADD COLUMN DMD_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
ADD COLUMN DMD_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
ADD COLUMN DMD_ACTIVE TINYINT(1) NOT NULL DEFAULT 1;