
CREATE TABLE OH_CONDITIONING (
    COND_ID INT AUTO_INCREMENT PRIMARY KEY,
    COND_PERFORMED_BY VARCHAR(50) NOT NULL,
    COND_ASPIRATION BOOLEAN,
    COND_CPAP BOOLEAN,
    COND_MCE INT,
    COND_VENTILATION INT,
    COND_OXYGEN_DEBIT DOUBLE,
    COND_SG_VOLUME DOUBLE,
    COND_DIAZEPAM_DOSE DOUBLE,
    COND_BOLUS_SS_VOLUME DOUBLE,
    COND_SNG_NUMBER VARCHAR(255),
    COND_OTHERS VARCHAR(255),
    COND_PAT_ID INT NOT NULL,
    COND_MALARIA VARCHAR(255),
    COND_HIV_TEST VARCHAR(50) DEFAULT 'INDETERMINATE',
    COND_BLOOD_GLUCOSE_LEVEL DOUBLE,
    COND_CONDITION_AT_ADMISSION LONGTEXT NULL,
    COND_PERFORMED_AT DATETIME,
    COND_CREATED_BY VARCHAR(255),
    COND_CREATED_DATE DATETIME,
    COND_LAST_MODIFIED_BY VARCHAR(255),
    COND_LAST_MODIFIED_DATE DATETIME,
    COND_ACTIVE BOOLEAN DEFAULT TRUE,
    COND_LOCK INT(11) NOT NULL DEFAULT 0,

    CONSTRAINT fk_conditioning_patient FOREIGN KEY (COND_PAT_ID)
        REFERENCES OH_PATIENT(PAT_ID)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_conditioning_user FOREIGN KEY (COND_PERFORMED_BY)
        REFERENCES OH_USER(US_ID_A)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
