ALTER TABLE OH_CONDITIONING
    CHANGE COLUMN COND_DUREE_MCE COND_MCE INT,
    CHANGE COLUMN COND_DUREE_VENTILATION COND_VENTILATION INT,
    CHANGE COLUMN COND_DEBIT_OXYGENE COND_OXYGEN_DEBIT DOUBLE,
    CHANGE COLUMN COND_SNG_NUMERO COND_SNG_NUMBER VARCHAR(255),
    CHANGE COLUMN COND_DATE COND_PERFORMED_AT DATETIME;

 ALTER TABLE oh_encounter ADD COLUMN ENC_PERFORMED_AT DATETIME NULL DEFAULT NULL;
 ALTER TABLE oh_encounter ADD COLUMN ENC_CLOSED_AT DATETIME NULL DEFAULT NULL;