CREATE TABLE oh_encounter (
    ENC_ID INT AUTO_INCREMENT PRIMARY KEY,
    ENC_CODE VARCHAR(255) NOT NULL UNIQUE,
    ENC_STATUS VARCHAR(20) NOT NULL DEFAULT 'OPEN',
    ENC_PAT_ID INT NOT NULL,
    ENC_LOCK int NOT NULL default 0,
    ENC_CREATED_BY VARCHAR(50) NULL DEFAULT NULL,
    ENC_CREATED_DATE datetime NULL DEFAULT NULL,
    ENC_LAST_MODIFIED_BY VARCHAR(50) NULL DEFAULT NULL,
    ENC_LAST_MODIFIED_DATE datetime NULL DEFAULT NULL,
    ENC_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CONSTRAINT fk_encounter_patient
        FOREIGN KEY (ENC_PAT_ID)
        REFERENCES oh_patient(PAT_ID)
        ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;