CREATE TABLE OH_TOWN (
    TW_ID INT AUTO_INCREMENT PRIMARY KEY,
    TW_NAME VARCHAR(255) NOT NULL,
    TW_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    TW_CREATED_BY VARCHAR(100),
    TW_CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TW_LAST_MODIFIED_BY VARCHAR(100),
    TW_LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_TOWN_NAME UNIQUE (TW_NAME)
);

INSERT INTO OH_TOWN (TW_NAME, TW_ACTIVE, TW_CREATED_BY, TW_CREATED_DATE, TW_LAST_MODIFIED_BY, TW_LAST_MODIFIED_DATE) VALUES ('Cotonou', 1, null, null, null, null);
INSERT INTO OH_TOWN (TW_NAME, TW_ACTIVE, TW_CREATED_BY, TW_CREATED_DATE, TW_LAST_MODIFIED_BY, TW_LAST_MODIFIED_DATE) VALUES ('Porto-Novo', 1, null, null, null, null);
INSERT INTO OH_TOWN (TW_NAME, TW_ACTIVE, TW_CREATED_BY, TW_CREATED_DATE, TW_LAST_MODIFIED_BY, TW_LAST_MODIFIED_DATE) VALUES ('Parakou', 1, null, null, null, null);
INSERT INTO OH_TOWN (TW_NAME, TW_ACTIVE, TW_CREATED_BY, TW_CREATED_DATE, TW_LAST_MODIFIED_BY, TW_LAST_MODIFIED_DATE) VALUES ('Abomey-Calavi', 1, null, null, null, null);
INSERT INTO OH_TOWN (TW_NAME, TW_ACTIVE, TW_CREATED_BY, TW_CREATED_DATE, TW_LAST_MODIFIED_BY, TW_LAST_MODIFIED_DATE) VALUES ('Bohicon', 1, null, null, null, null);
INSERT INTO OH_TOWN (TW_NAME, TW_ACTIVE, TW_CREATED_BY, TW_CREATED_DATE, TW_LAST_MODIFIED_BY, TW_LAST_MODIFIED_DATE) VALUES ('Natitingou', 1, null, null, null, null);
INSERT INTO OH_TOWN (TW_NAME, TW_ACTIVE, TW_CREATED_BY, TW_CREATED_DATE, TW_LAST_MODIFIED_BY, TW_LAST_MODIFIED_DATE) VALUES ('Djougou', 1, null, null, null, null);
INSERT INTO OH_TOWN (TW_NAME, TW_ACTIVE, TW_CREATED_BY, TW_CREATED_DATE, TW_LAST_MODIFIED_BY, TW_LAST_MODIFIED_DATE) VALUES ('Ouidah', 1, null, null, null, null);
INSERT INTO OH_TOWN (TW_NAME, TW_ACTIVE, TW_CREATED_BY, TW_CREATED_DATE, TW_LAST_MODIFIED_BY, TW_LAST_MODIFIED_DATE) VALUES('Lokossa', 1, null, null, null, null);
INSERT INTO OH_TOWN (TW_NAME, TW_ACTIVE, TW_CREATED_BY, TW_CREATED_DATE, TW_LAST_MODIFIED_BY, TW_LAST_MODIFIED_DATE) VALUES ('Kandi', 1, null, null, null, null);

CREATE TABLE OH_ETHNIC (
    ETH_ID INT AUTO_INCREMENT PRIMARY KEY,
    ETH_NAME VARCHAR(255) NOT NULL,
    ETH_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    ETH_CREATED_BY VARCHAR(100),
    ETH_CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ETH_LAST_MODIFIED_BY VARCHAR(100),
    ETH_LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_ETHNIC_NAME UNIQUE (ETH_NAME)
);

INSERT INTO OH_ETHNIC (ETH_NAME, ETH_ACTIVE, ETH_CREATED_BY, ETH_CREATED_DATE, ETH_LAST_MODIFIED_BY, ETH_LAST_MODIFIED_DATE) VALUES ('Idactha', 1, null, null, null, null);
INSERT INTO OH_ETHNIC (ETH_NAME, ETH_ACTIVE, ETH_CREATED_BY, ETH_CREATED_DATE, ETH_LAST_MODIFIED_BY, ETH_LAST_MODIFIED_DATE) VALUES ('Nogot', 1, null, null, null, null);
INSERT INTO OH_ETHNIC (ETH_NAME, ETH_ACTIVE, ETH_CREATED_BY, ETH_CREATED_DATE, ETH_LAST_MODIFIED_BY, ETH_LAST_MODIFIED_DATE) VALUES ('Ife', 1, null, null, null, null);
INSERT INTO OH_ETHNIC (ETH_NAME, ETH_ACTIVE, ETH_CREATED_BY, ETH_CREATED_DATE, ETH_LAST_MODIFIED_BY, ETH_LAST_MODIFIED_DATE) VALUES ('Fon', 1, null, null, null, null);
INSERT INTO OH_ETHNIC (ETH_NAME, ETH_ACTIVE, ETH_CREATED_BY, ETH_CREATED_DATE, ETH_LAST_MODIFIED_BY, ETH_LAST_MODIFIED_DATE) VALUES ('Peulh', 1, null, null, null, null);
INSERT INTO OH_ETHNIC (ETH_NAME, ETH_ACTIVE, ETH_CREATED_BY, ETH_CREATED_DATE, ETH_LAST_MODIFIED_BY, ETH_LAST_MODIFIED_DATE) VALUES ('Adja', 1, null, null, null, null);

CREATE TABLE OH_COMMUNE (
    COM_ID INT AUTO_INCREMENT PRIMARY KEY,
    COM_NAME VARCHAR(255) NOT NULL,
    COM_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    COM_CREATED_BY VARCHAR(100),
    COM_CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    COM_LAST_MODIFIED_BY VARCHAR(100),
    COM_LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_COMMUNE_NAME UNIQUE (COM_NAME)
);

INSERT INTO OH_COMMUNE (COM_NAME, COM_ACTIVE, COM_CREATED_BY, COM_CREATED_DATE, COM_LAST_MODIFIED_BY, COM_LAST_MODIFIED_DATE) VALUES ('Dassa', 1, null, null, null, null);
INSERT INTO OH_COMMUNE (COM_NAME, COM_ACTIVE, COM_CREATED_BY, COM_CREATED_DATE, COM_LAST_MODIFIED_BY, COM_LAST_MODIFIED_DATE) VALUES ('Glazoue', 1, null, null, null, null);
INSERT INTO OH_COMMUNE (COM_NAME, COM_ACTIVE, COM_CREATED_BY, COM_CREATED_DATE, COM_LAST_MODIFIED_BY, COM_LAST_MODIFIED_DATE) VALUES ('Savalou', 1, null, null, null, null);

CREATE TABLE OH_OCCUPATION (
    OCC_ID INT AUTO_INCREMENT PRIMARY KEY,
    OCC_NAME VARCHAR(255) NOT NULL,
    OCC_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    OCC_CREATED_BY VARCHAR(100),
    OCC_CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OCC_LAST_MODIFIED_BY VARCHAR(100),
    OCC_LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT UQ_OH_OCCUPATION_NAME UNIQUE (OCC_NAME)
);

INSERT INTO OH_OCCUPATION (OCC_NAME, OCC_ACTIVE, OCC_CREATED_BY, OCC_CREATED_DATE, OCC_LAST_MODIFIED_BY, OCC_LAST_MODIFIED_DATE) VALUES ('Médecin', 1, null, null, null, null);
INSERT INTO OH_OCCUPATION (OCC_NAME, OCC_ACTIVE, OCC_CREATED_BY, OCC_CREATED_DATE, OCC_LAST_MODIFIED_BY, OCC_LAST_MODIFIED_DATE) VALUES ('Infirmier', 1, null, null, null, null);
INSERT INTO OH_OCCUPATION (OCC_NAME, OCC_ACTIVE, OCC_CREATED_BY, OCC_CREATED_DATE, OCC_LAST_MODIFIED_BY, OCC_LAST_MODIFIED_DATE) VALUES ('Enseignant', 1, null, null, null, null);
INSERT INTO OH_OCCUPATION (OCC_NAME, OCC_ACTIVE, OCC_CREATED_BY, OCC_CREATED_DATE, OCC_LAST_MODIFIED_BY, OCC_LAST_MODIFIED_DATE) VALUES ('Avocat', 1, null, null, null, null);
INSERT INTO OH_OCCUPATION (OCC_NAME, OCC_ACTIVE, OCC_CREATED_BY, OCC_CREATED_DATE, OCC_LAST_MODIFIED_BY, OCC_LAST_MODIFIED_DATE) VALUES ('Comptable', 1, null, null, null, null);
INSERT INTO OH_OCCUPATION (OCC_NAME, OCC_ACTIVE, OCC_CREATED_BY, OCC_CREATED_DATE, OCC_LAST_MODIFIED_BY, OCC_LAST_MODIFIED_DATE) VALUES ('Électricien', 1, null, null, null, null);
INSERT INTO OH_OCCUPATION (OCC_NAME, OCC_ACTIVE, OCC_CREATED_BY, OCC_CREATED_DATE, OCC_LAST_MODIFIED_BY, OCC_LAST_MODIFIED_DATE) VALUES ('Mécanicien', 1, null, null, null, null);
INSERT INTO OH_OCCUPATION (OCC_NAME, OCC_ACTIVE, OCC_CREATED_BY, OCC_CREATED_DATE, OCC_LAST_MODIFIED_BY, OCC_LAST_MODIFIED_DATE) VALUES ('Journaliste', 1, null, null, null, null);
INSERT INTO OH_OCCUPATION (OCC_NAME, OCC_ACTIVE, OCC_CREATED_BY, OCC_CREATED_DATE, OCC_LAST_MODIFIED_BY, OCC_LAST_MODIFIED_DATE) VALUES ('Entrepreneur', 1, null, null, null, null);