ALTER TABLE OH_PATIENTEXAMINATION
ADD COLUMN PEX_BODY_MASS_INDEX  DOUBLE NULL DEFAULT NULL COMMENT 'BMI in Kg/m2',
ADD COLUMN PEX_PC DOUBLE NULL DEFAULT NULL,
ADD COLUMN PEX_BRANCHIAL_PERIMETER DOUBLE NULL DEFAULT NULL COMMENT 'PB in cm';
