ALTER TABLE OH_ADMISSION 
DROP FOREIGN KEY FK_ADMISSION_OPERATION;

ALTER TABLE OH_ADMISSION 
DROP COLUMN ADM_RESOP,
DROP COLUMN ADM_DATE_OP,
DROP COLUMN ADM_OPE_ID_A,
DROP INDEX FK_ADMISSION_OPERATION;
