ALTER TABLE OH_CONDITIONING ADD COLUMN COND_TDR VARCHAR(255) NULL;
ALTER TABLE OH_CONDITIONING ADD COLUMN COND_CONDITION_AT_ADMISSION longtext NULL;

ALTER TABLE OH_ADMISSION DROP COLUMN ADM_CONDITION_AT_ADMISSION;