CREATE TABLE OH_USER_SETTINGS (
 USS_ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, 
 USS_US_ID_A int(11) NOT NULL, 
 USS_CONFIG_NAME  VARCHAR(100) NOT NULL,  
 USS_CONFIG_VALUE VARCHAR(max) NOT NULL,
 PRIMARY KEY (USS_ID),
 FOREIGN KEY (USS_US_ID_A) REFERENCES OH_USER(US_ID) ON DELETE CASCADE, 
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;