CREATE TABLE OH_CONDITIONING (
    COND_ID INT AUTO_INCREMENT PRIMARY KEY,
    COND_ASPIRATION BOOLEAN,
    COND_DUREE_MCE INT,
    COND_DUREE_VENTILATION INT,
    COND_DEBIT_OXYGENE DOUBLE,
    COND_SG_VOLUME DOUBLE,
    COND_DIAZEPAM_DOSE DOUBLE,
    COND_BOLUS_SS_VOLUME DOUBLE,
    COND_SNG_NUMERO VARCHAR(255),
    COND_OTHERS VARCHAR(255),
    COND_US_ID VARCHAR(50) NOT NULL,
    COND_PERFORM_AT DATETIME,
    COND_CREATED_BY VARCHAR(255),
    COND_CREATED_DATE DATETIME,
    COND_LAST_MODIFIED_BY VARCHAR(255),
    COND_LAST_MODIFIED_DATE DATETIME,
    COND_ACTIVE BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_conditioning_user FOREIGN KEY (COND_US_ID)
        REFERENCES OH_USER(US_ID_A)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
