-- OP-1005: add DELETED_BY / DELETED_DATE audit columns to the soft-deletable tables, so soft deletions can be
-- audited (who and when) like creations and modifications. The columns mirror the existing *_LAST_MODIFIED_BY /
-- *_LAST_MODIFIED_DATE audit columns and stay NULL until a row is soft-deleted; DELETED_BY is a foreign key to
-- OH_USER like every other *_BY audit column (see step_a115).
--
-- Only the entities that actually perform a soft delete are included (Patient, Admission, Supplier, User,
-- UserGroup). Medical and MedicalType carry a *_DELETED flag but their delete is currently physical, so they are
-- intentionally left out until a soft delete is implemented for them.

ALTER TABLE OH_ADMISSION
	ADD COLUMN ADM_DELETED_BY VARCHAR(50) NULL DEFAULT NULL,
	ADD COLUMN ADM_DELETED_DATE datetime NULL DEFAULT NULL,
	ADD CONSTRAINT FK_ADMISSION_DELETED_BY FOREIGN KEY (ADM_DELETED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OH_SUPPLIER
	ADD COLUMN SUP_DELETED_BY VARCHAR(50) NULL DEFAULT NULL,
	ADD COLUMN SUP_DELETED_DATE datetime NULL DEFAULT NULL,
	ADD CONSTRAINT FK_SUPPLIER_DELETED_BY FOREIGN KEY (SUP_DELETED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OH_PATIENT
	ADD COLUMN PAT_DELETED_BY VARCHAR(50) NULL DEFAULT NULL,
	ADD COLUMN PAT_DELETED_DATE datetime NULL DEFAULT NULL,
	ADD CONSTRAINT FK_PATIENT_DELETED_BY FOREIGN KEY (PAT_DELETED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OH_USER
	ADD COLUMN US_DELETED_BY VARCHAR(50) NULL DEFAULT NULL,
	ADD COLUMN US_DELETED_DATE datetime NULL DEFAULT NULL,
	ADD CONSTRAINT FK_USER_DELETED_BY FOREIGN KEY (US_DELETED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OH_USERGROUP
	ADD COLUMN UG_DELETED_BY VARCHAR(50) NULL DEFAULT NULL,
	ADD COLUMN UG_DELETED_DATE datetime NULL DEFAULT NULL,
	ADD CONSTRAINT FK_USERGROUP_DELETED_BY FOREIGN KEY (UG_DELETED_BY) REFERENCES OH_USER (US_ID_A) ON DELETE NO ACTION ON UPDATE NO ACTION;
