ALTER TABLE oh_medicalhistory
MODIFY COLUMN MH_DEPARASITI BOOLEAN,

DROP COLUMN MH_VACC_STATE,
ADD COLUMN MH_VACC_STATE_PREV VARCHAR(255) NULL,
ADD COLUMN MH_VACC_STATE_NO_PREV VARCHAR(255) NULL,

DROP COLUMN MH_ANTI_MLRIAL_PROPHY,
ADD COLUMN MH_ANTI_MLRIAL_PROPHY_MILDA VARCHAR(255) NULL,
ADD COLUMN MH_ANTI_MLRIAL_PROPHY_VAP VARCHAR(255) NULL,
ADD COLUMN MH_ANTI_MLRIAL_PROPHY_OTHERS VARCHAR(255) NULL,

ADD COLUMN MH_REASON_MODE VARCHAR(255) NULL,
ADD COLUMN MH_DIVERSIFICATION VARCHAR(255) NULL,
ADD COLUMN MH_NEONATAL_PERIOD VARCHAR(255) NULL,
ADD COLUMN MH_PREVIOUS_HOSPITALIZATION VARCHAR(255) NULL,
ADD COLUMN MH_FATHER VARCHAR(255) NULL,
ADD COLUMN MH_MOTHER VARCHAR(255) NULL,
ADD COLUMN MH_SIBLINGS INT NULL,
ADD COLUMN MH_OTHER_USEFUL_INFORMATION VARCHAR(255) NULL;
