CREATE TABLE OH_SESSION (
  SES_ID INT(11) NOT NULL AUTO_INCREMENT,
  SES_US_ID_A VARCHAR(50) NOT NULL,
  SES_LOGIN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  SES_LOGOUT TIMESTAMP NULL,
  PRIMARY KEY (SES_ID)
);