-- OP-1037: administrative issues raised by the hospital on a patient (a missing document, an identity to verify, an open
-- dispute). While at least one issue is open (PAI_TO IS NULL) the staff is warned before providing further services.
-- Resolving an issue only sets PAI_TO, so who raised it, when, and when it was cleared stay on record.
CREATE TABLE OH_PATIENT_ADMIN_ISSUE (
	PAI_ID INT NOT NULL AUTO_INCREMENT,
	PAI_PAT_ID INT NOT NULL,
	PAI_REASON VARCHAR(255) NOT NULL,
	PAI_FROM DATETIME NOT NULL,
	PAI_TO DATETIME NULL DEFAULT NULL,
	PAI_CREATED_BY VARCHAR(50) DEFAULT NULL,
	PAI_CREATED_DATE DATETIME DEFAULT NULL,
	PAI_LAST_MODIFIED_BY VARCHAR(50) DEFAULT NULL,
	PAI_LAST_MODIFIED_DATE DATETIME DEFAULT NULL,
	PAI_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (PAI_ID),
	KEY FK_PATIENT_ADMIN_ISSUE_PATIENT (PAI_PAT_ID),
	CONSTRAINT FK_PATIENT_ADMIN_ISSUE_PATIENT FOREIGN KEY (PAI_PAT_ID) REFERENCES OH_PATIENT (PAT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB;
