-- extend WRD_ID_A to CHAR(3) and update all its references
-- drop foreing keys and indexes
ALTER TABLE OH_ADMISSION DROP FOREIGN KEY FK_ADMISSION_WARD;
ALTER TABLE OH_ADMISSION DROP INDEX FK_ADMISSION_WARD;
ALTER TABLE OH_MEDICALDSRSTOCKMOV DROP FOREIGN KEY FK_MEDICALDSRSTOCKMOV_WARD;
ALTER TABLE OH_MEDICALDSRSTOCKMOV DROP INDEX FK_MEDICALDSRSTOCKMOV_WARD;
ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD DROP FOREIGN KEY FK_MEDICALDSRSTOCKMOVWARD_WARD;
ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD DROP INDEX FK_MEDICALDSRSTOCKMOVWARD_WARD_idx;
ALTER TABLE OH_MEDICALDSRWARD DROP FOREIGN KEY FK_MEDICALDSRWARD_WARD;
ALTER TABLE OH_MEDICALDSRWARD DROP INDEX FK_MEDICALDSRWARD_WARD_idx;
ALTER TABLE OH_VISITS DROP FOREIGN KEY FK_VISITS_WARD;
ALTER TABLE OH_VISITS DROP INDEX FK_VISITS_WARD;

-- change columns types
ALTER TABLE OH_WARD MODIFY COLUMN WRD_ID_A CHAR(3) NOT NULL DEFAULT '' ;
ALTER TABLE OH_ADMISSION MODIFY COLUMN ADM_WRD_ID_A CHAR(3) NOT NULL DEFAULT '' ;
ALTER TABLE OH_MEDICALDSRWARD MODIFY COLUMN MDSRWRD_WRD_ID_A CHAR(3) NOT NULL DEFAULT '';
ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD MODIFY COLUMN MMVN_WRD_ID_A CHAR(3) NOT NULL DEFAULT '';
ALTER TABLE OH_MEDICALDSRSTOCKMOV MODIFY COLUMN MMV_WRD_ID_A CHAR(3) DEFAULT '';
ALTER TABLE OH_VISITS MODIFY COLUMN VST_WRD_ID_A CHAR(3) DEFAULT '';

-- add again foreing keys and indexes
ALTER TABLE OH_ADMISSION
	ADD CONSTRAINT FK_ADMISSION_WARD
	    FOREIGN KEY (ADM_WRD_ID_A )
	    REFERENCES OH_WARD (WRD_ID_A )
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	ADD INDEX FK_ADMISSION_WARD_idx (ADM_WRD_ID_A ASC);

ALTER TABLE OH_MEDICALDSRSTOCKMOV
 	ADD CONSTRAINT FK_MEDICALDSRSTOCKMOV_WARD
	    FOREIGN KEY (MMV_WRD_ID_A )
	    REFERENCES OH_WARD (WRD_ID_A )
	    ON DELETE NO ACTION
    	ON UPDATE NO ACTION,
	ADD INDEX FK_MEDICALDSRSTOCKMOV_WARD_idx (MMV_WRD_ID_A ASC);

ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD  	
    ADD CONSTRAINT FK_MEDICALDSRSTOCKMOVWARD_WARD
	    FOREIGN KEY (MMVN_WRD_ID_A )
	    REFERENCES OH_WARD (WRD_ID_A )
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	ADD INDEX FK_MEDICALDSRSTOCKMOVWARD_WARD_idx (MMVN_WRD_ID_A ASC);

ALTER TABLE OH_MEDICALDSRWARD  	    
 	ADD CONSTRAINT FK_MEDICALDSRWARD_WARD
	    FOREIGN KEY (MDSRWRD_WRD_ID_A )
	    REFERENCES OH_WARD (WRD_ID_A )
	    ON DELETE NO ACTION
	    ON UPDATE NO ACTION,
	ADD INDEX FK_MEDICALDSRWARD_WARD_idx (MDSRWRD_WRD_ID_A ASC);
        
ALTER TABLE OH_VISITS
	ADD CONSTRAINT FK_VISITS_WARD 
		FOREIGN KEY (VST_WRD_ID_A) 
        REFERENCES OH_WARD (WRD_ID_A) 
        ON DELETE NO ACTION 
        ON UPDATE NO ACTION,
	ADD INDEX FK_VISITS_WARD_idx (VST_WRD_ID_A ASC);
	
-- add new field to WARD table
ALTER TABLE OH_WARD ADD COLUMN WRD_HAS_OPD TINYINT(1) NOT NULL DEFAULT '0' AFTER WRD_NDOC;
INSERT INTO OH_WARD (WRD_ID_A, WRD_NAME, WRD_TELE, WRD_FAX, WRD_EMAIL, WRD_NBEDS, WRD_NQUA_NURS, WRD_NDOC, WRD_HAS_OPD, WRD_IS_PHARMACY, WRD_IS_MALE, WRD_IS_FEMALE, WRD_VISIT_DURATION, WRD_LOCK, WRD_CREATED_BY, WRD_CREATED_DATE, WRD_ACTIVE) 
VALUES ('OPD', 'OPD', 212, '', '', '0', '1', '1', '1', '1', '1', '1', '5', '0', 'admin', NOW(), '1');
