ALTER TABLE `oh`.`oh_medicaldsrstockmovward` 
CHANGE COLUMN `MMVN_WRD_ID_A_FROM` `MMVN_WRD_ID_A_FROM` CHAR(3) NULL DEFAULT NULL ,
CHANGE COLUMN `MMVN_WRD_ID_A_TO` `MMVN_WRD_ID_A_TO` CHAR(3) NULL DEFAULT NULL ;
