ALTER TABLE `oh_admission` 
ADD INDEX `FK_ADMISSION_USER_IDX` (`ADM_USR_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_admission` 
ADD CONSTRAINT `FK_ADMISSION_USER`
  FOREIGN KEY (`ADM_USR_ID_A`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_billpayments` 
ADD INDEX `FK_BILLPAYMENTS_USER_IDX` (`BLP_USR_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_billpayments` 
ADD CONSTRAINT `FK_BILLPAYMENTS_USER`
  FOREIGN KEY (`BLP_USR_ID_A`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  

ALTER TABLE `oh_bills` 
ADD INDEX `FK_BILLS_USER_IDX` (`BLL_USR_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_bills` 
ADD CONSTRAINT `FK_BILLS_USER`
  FOREIGN KEY (`BLL_USR_ID_A`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE `oh_opd` 
ADD INDEX `FK_OPD_USER_IDX` (`OPD_USR_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_opd` 
ADD CONSTRAINT `FK_OPD_USER`
  FOREIGN KEY (`OPD_USR_ID_A`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE `oh_session_audit`
DROP FOREIGN KEY `oh_session_audit_ibfk_1`;
;
ALTER TABLE `oh_session_audit`
ADD CONSTRAINT `FK_SESSION_AUDIT_USER`
    FOREIGN KEY (`SEA_US_ID_A`)
    REFERENCES `oh_user` (`US_ID_A`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;