CREATE TABLE OH_MEDICALDSRSTOCKMOV_LOG (
	MMVL_ID INT NOT NULL AUTO_INCREMENT,
	MMVL_MMV_ID INT NOT NULL,
	MMVL_MDSR_ID INT NOT NULL,
	MMVL_MMVT_ID_A VARCHAR(10) NOT NULL,
	MMVL_WRD_ID_A CHAR(3) NULL,
	MMVL_LT_ID_A VARCHAR(50) NULL,
	MMVL_DATE DATETIME NOT NULL,
	MMVL_QTY INT NOT NULL DEFAULT 0,
	MMVL_REFNO VARCHAR(50) NULL,
	MMVL_REASON VARCHAR(255) NULL,
	MMVL_CREATED_BY VARCHAR(50) DEFAULT NULL,
	MMVL_CREATED_DATE DATETIME DEFAULT NULL,
	MMVL_LAST_MODIFIED_BY VARCHAR(50) DEFAULT NULL,
	MMVL_LAST_MODIFIED_DATE DATETIME DEFAULT NULL,
	MMVL_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (MMVL_ID)
) ENGINE=InnoDB;

CREATE TABLE OH_MEDICALDSRSTOCKMOVWARD_LOG (
	MMVNL_ID INT NOT NULL AUTO_INCREMENT,
	MMVNL_MMVN_ID INT NOT NULL,
	MMVNL_WRD_ID_A CHAR(3) NOT NULL,
	MMVNL_DATE DATETIME NOT NULL,
	MMVNL_IS_PATIENT TINYINT(1) NOT NULL DEFAULT 0,
	MMVNL_PAT_ID INT DEFAULT NULL,
	MMVNL_MDSR_ID INT NOT NULL,
	MMVNL_MDSR_QTY FLOAT NOT NULL DEFAULT 0,
	MMVNL_MDSR_UNITS VARCHAR(10) NULL,
	MMVNL_DESC VARCHAR(100) NULL,
	MMVNL_LT_ID VARCHAR(50) DEFAULT NULL,
	MMVNL_REASON VARCHAR(255) NULL,
	MMVNL_CREATED_BY VARCHAR(50) DEFAULT NULL,
	MMVNL_CREATED_DATE DATETIME DEFAULT NULL,
	MMVNL_LAST_MODIFIED_BY VARCHAR(50) DEFAULT NULL,
	MMVNL_LAST_MODIFIED_DATE DATETIME DEFAULT NULL,
	MMVNL_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
	PRIMARY KEY (MMVNL_ID)
) ENGINE=InnoDB;
