-- OP-1427 (stage 1): introduce an internal numeric lot id (LT_ID) as the primary key of OH_MEDICALDSRLOT.
-- The printed lot number (LT_ID_A) remains globally UNIQUE and remains the business identifier shown to the users.

-- add the new auto-increment id to the lot table (AUTO_INCREMENT requires a key until the primary key swap below)
ALTER TABLE OH_MEDICALDSRLOT
ADD COLUMN LT_ID INT NOT NULL AUTO_INCREMENT FIRST,
ADD UNIQUE KEY UK_MEDICALDSRLOT_LT_ID (LT_ID);

-- add the numeric foreign key columns to the child tables
ALTER TABLE OH_MEDICALDSRSTOCKMOV ADD COLUMN MMV_LT_ID INT NULL AFTER MMV_LT_ID_A;

ALTER TABLE OH_MEDICALDSRWARD ADD COLUMN MDSRWRD_LT_ID INT NULL AFTER MDSRWRD_LT_ID_A;

ALTER TABLE OH_MEDICALDSRINVENTORYROW ADD COLUMN MINVTR_LT_ID INT NULL AFTER MINVTR_LT_ID_A;

-- OH_MEDICALDSRSTOCKMOVWARD already names its varchar lot column MMVN_LT_ID: drop its foreign key,
-- move the lot codes to MMVN_LT_ID_A and reuse the MMVN_LT_ID name for the numeric foreign key
ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD DROP FOREIGN KEY FK_MEDICALDSRSTOCKMOVWARD_LOT;

ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD CHANGE COLUMN MMVN_LT_ID MMVN_LT_ID_A VARCHAR(50) NULL;

ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD ADD COLUMN MMVN_LT_ID INT NULL AFTER MMVN_LT_ID_A;

-- backfill the numeric columns through the (unique) lot code
UPDATE OH_MEDICALDSRSTOCKMOV JOIN OH_MEDICALDSRLOT ON MMV_LT_ID_A = LT_ID_A SET MMV_LT_ID = LT_ID;

UPDATE OH_MEDICALDSRWARD JOIN OH_MEDICALDSRLOT ON MDSRWRD_LT_ID_A = LT_ID_A SET MDSRWRD_LT_ID = LT_ID;

UPDATE OH_MEDICALDSRINVENTORYROW JOIN OH_MEDICALDSRLOT ON MINVTR_LT_ID_A = LT_ID_A SET MINVTR_LT_ID = LT_ID;

UPDATE OH_MEDICALDSRSTOCKMOVWARD JOIN OH_MEDICALDSRLOT ON MMVN_LT_ID_A = LT_ID_A SET MMVN_LT_ID = LT_ID;

-- drop the varchar lot columns on the tables that had a real foreign key on them (every row there matched a lot).
-- OH_MEDICALDSRSTOCKMOV.MMV_LT_ID_A had no foreign key, so legacy movements may reference lot codes that no longer
-- exist: those rows keep MMV_LT_ID = NULL and MMV_LT_ID_A is kept as a plain column to avoid any data loss.
ALTER TABLE OH_MEDICALDSRWARD DROP FOREIGN KEY FK_MEDICALDSRWARD_MEDICALDSRLOT;

ALTER TABLE OH_MEDICALDSRWARD MODIFY COLUMN MDSRWRD_LT_ID INT NOT NULL;

ALTER TABLE OH_MEDICALDSRWARD
DROP PRIMARY KEY,
ADD PRIMARY KEY (MDSRWRD_WRD_ID_A, MDSRWRD_MDSR_ID, MDSRWRD_LT_ID);

ALTER TABLE OH_MEDICALDSRWARD DROP COLUMN MDSRWRD_LT_ID_A;

ALTER TABLE OH_MEDICALDSRINVENTORYROW DROP FOREIGN KEY FK_MEDICALDSRINVENTORYROW_MEDICALDSRLOT;

ALTER TABLE OH_MEDICALDSRINVENTORYROW DROP COLUMN MINVTR_LT_ID_A;

ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD DROP COLUMN MMVN_LT_ID_A;

-- swap the primary key of the lot table: LT_ID becomes the primary key, LT_ID_A stays UNIQUE (stage 1)
ALTER TABLE OH_MEDICALDSRLOT
DROP PRIMARY KEY,
ADD PRIMARY KEY (LT_ID),
DROP KEY UK_MEDICALDSRLOT_LT_ID,
ADD UNIQUE KEY UK_MEDICALDSRLOT_LT_ID_A (LT_ID_A);

-- add the new foreign keys on the numeric columns (NULL allowed on OH_MEDICALDSRSTOCKMOV.MMV_LT_ID)
ALTER TABLE OH_MEDICALDSRSTOCKMOV
ADD CONSTRAINT FK_MEDICALDSRSTOCKMOV_MEDICALDSRLOT
FOREIGN KEY (MMV_LT_ID) REFERENCES OH_MEDICALDSRLOT (LT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OH_MEDICALDSRWARD
ADD CONSTRAINT FK_MEDICALDSRWARD_MEDICALDSRLOT
FOREIGN KEY (MDSRWRD_LT_ID) REFERENCES OH_MEDICALDSRLOT (LT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD
ADD CONSTRAINT FK_MEDICALDSRSTOCKMOVWARD_LOT
FOREIGN KEY (MMVN_LT_ID) REFERENCES OH_MEDICALDSRLOT (LT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE OH_MEDICALDSRINVENTORYROW
ADD CONSTRAINT FK_MEDICALDSRINVENTORYROW_MEDICALDSRLOT
FOREIGN KEY (MINVTR_LT_ID) REFERENCES OH_MEDICALDSRLOT (LT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION;
