CREATE  TABLE OH_PATIENTSTP (
	STP_PAT_ID INT(11) NOT NULL ,
	STP_CODE VARCHAR(16) NOT NULL ,
	STP_ISSUE_DATE DATETIME NOT NULL ,
	STP_RENEW_DATE DATETIME ,
	STP_EXPIRY_DATE DATETIME NOT NULL ,
	STP_IMMIGRATION_DATE DATETIME NULL ,
	STP_HOMELAND VARCHAR(50),
	PRIMARY KEY (STP_PAT_ID)
) ENGINE = MyISAM;

--
-- CONSTRAINTS
--
ALTER TABLE OH_PATIENTSTP
	ADD CONSTRAINT FK_STP_PATIENT
	FOREIGN KEY (STP_PAT_ID)
	REFERENCES PATIENT (PAT_ID)
	ON DELETE CASCADE
	ON UPDATE CASCADE;