ALTER TABLE `oh_admission` 
ADD INDEX `FK_ADMISSION_USER_IDX` (`ADM_USR_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_admission` 
ADD CONSTRAINT `FK_ADMISSION_USER`
  FOREIGN KEY (`ADM_USR_ID_A`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_billpayments` 
ADD INDEX `FK_BILLPAYMENTS_USER_IDX` (`BLP_USR_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_billpayments` 
ADD CONSTRAINT `FK_BILLPAYMENTS_USER`
  FOREIGN KEY (`BLP_USR_ID_A`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  

ALTER TABLE `oh_bills` 
ADD INDEX `FK_BILLS_USER_IDX` (`BLL_USR_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_bills` 
ADD CONSTRAINT `FK_BILLS_USER`
  FOREIGN KEY (`BLL_USR_ID_A`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE `oh_opd` 
ADD INDEX `FK_OPD_USER_IDX` (`OPD_USR_ID_A` ASC) VISIBLE;
;
ALTER TABLE `oh_opd` 
ADD CONSTRAINT `FK_OPD_USER`
  FOREIGN KEY (`OPD_USR_ID_A`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
ALTER TABLE `oh_session_audit`
DROP FOREIGN KEY `oh_session_audit_ibfk_1`;
;
ALTER TABLE `oh_session_audit`
ADD CONSTRAINT `FK_SESSION_AUDIT_USER`
    FOREIGN KEY (`SEA_US_ID_A`)
    REFERENCES `oh_user` (`US_ID_A`)
    ON DELETE CASCADE
    ON UPDATE CASCADE;
    
ALTER TABLE `oh_admission` 
ADD INDEX `FK_ADMISSION_CREATED_BY_IDX` (`ADM_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_admission` 
ADD CONSTRAINT `FK_ADMISSION_CREATED_BY`
  FOREIGN KEY (`ADM_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_admissiontype` 
ADD INDEX `FK_ADMISSIONTYPE_CREATED_BY_IDX` (`ADMT_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_admissiontype` 
ADD CONSTRAINT `FK_ADMISSIONTYPE_CREATED_BY`
  FOREIGN KEY (`ADMT_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_agetype` 
ADD INDEX `FK_AGETYPE_CREATED_BY_IDX` (`AT_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_agetype` 
ADD CONSTRAINT `FK_AGETYPE_CREATED_BY`
  FOREIGN KEY (`AT_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_billitems` 
ADD INDEX `FK_BILLITEMS_CREATED_BY_IDX` (`BLI_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_billitems` 
ADD CONSTRAINT `FK_BILLITEMS_CREATED_BY`
  FOREIGN KEY (`BLI_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_billpayments` 
ADD INDEX `FK_BILLPAYMENTS_CREATED_BY_IDX` (`BLP_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_billpayments` 
ADD CONSTRAINT `FK_BILLPAYMENTS_CREATED_BY`
  FOREIGN KEY (`BLP_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_bills` 
ADD INDEX `FK_BILLS_CREATED_BY_IDX` (`BLL_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_bills` 
ADD CONSTRAINT `FK_BILLS_CREATED_BY`
  FOREIGN KEY (`BLL_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_deliveryresulttype` 
ADD INDEX `FK_DELIVERYRESULTTYPE_CREATED_BY_IDX` (`DRT_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_deliveryresulttype` 
ADD CONSTRAINT `FK_DELIVERYRESULTTYPE_CREATED_BY`
  FOREIGN KEY (`DRT_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_deliverytype` 
ADD INDEX `FK_DELIVERYTYPE_CREATED_BY_IDX` (`DLT_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_deliverytype` 
ADD CONSTRAINT `FK_DELIVERYTYPE_CREATED_BY`
  FOREIGN KEY (`DLT_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_dicom` 
ADD INDEX `FK_DICOM_CREATED_BY_IDX` (`DM_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_dicom` 
ADD CONSTRAINT `FK_DICOM_CREATED_BY`
  FOREIGN KEY (`DM_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_dischargetype` 
ADD INDEX `FK_DISCHARGETYPE_CREATED_BY_IDX` (`DIST_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_dischargetype` 
ADD CONSTRAINT `FK_DISCHARGETYPE_CREATED_BY`
  FOREIGN KEY (`DIST_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_disease` 
ADD INDEX `FK_DISEASE_CREATED_BY_IDX` (`DIS_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_disease` 
ADD CONSTRAINT `FK_DISEASE_CREATED_BY`
  FOREIGN KEY (`DIS_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_diseasetype` 
ADD INDEX `FK_DISEASETYPE_CREATED_BY_IDX` (`DCL_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_diseasetype` 
ADD CONSTRAINT `FK_DISEASETYPE_CREATED_BY`
  FOREIGN KEY (`DCL_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_exam` 
ADD INDEX `FK_EXAM_CREATED_BY_IDX` (`EXA_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_exam` 
ADD CONSTRAINT `FK_EXAM_CREATED_BY`
  FOREIGN KEY (`EXA_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_examrow` 
ADD INDEX `FK_EXAMROW_CREATED_BY_IDX` (`EXR_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_examrow` 
ADD CONSTRAINT `FK_EXAMROW_CREATED_BY`
  FOREIGN KEY (`EXR_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_examtype` 
ADD INDEX `FK_EXAMTYPE_CREATED_BY_IDX` (`EXC_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_examtype` 
ADD CONSTRAINT `FK_EXAMTYPE_CREATED_BY`
  FOREIGN KEY (`EXC_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_groupmenu` 
ADD INDEX `FK_GROUPMENU_CREATED_BY_IDX` (`GM_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_groupmenu` 
ADD CONSTRAINT `FK_GROUPMENU_CREATED_BY`
  FOREIGN KEY (`GM_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_grouppermission` 
ADD INDEX `FK_GROUPPERMISSION_CREATED_BY_IDX` (`GP_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_grouppermission` 
ADD CONSTRAINT `FK_GROUPPERMISSION_CREATED_BY`
  FOREIGN KEY (`GP_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_hospital` 
ADD INDEX `FK_HOSPITAL_CREATED_BY_IDX` (`HOS_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_hospital` 
ADD CONSTRAINT `FK_HOSPITAL_CREATED_BY`
  FOREIGN KEY (`HOS_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_laboratory` 
ADD INDEX `FK_LABORATORY_CREATED_BY_IDX` (`LAB_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_laboratory` 
ADD CONSTRAINT `FK_LABORATORY_CREATED_BY`
  FOREIGN KEY (`LAB_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_laboratoryrow` 
ADD INDEX `FK_LABORATORYROW_CREATED_BY_IDX` (`LABR_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_laboratoryrow` 
ADD CONSTRAINT `FK_LABORATORYROW_CREATED_BY`
  FOREIGN KEY (`LABR_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_malnutritioncontrol` 
ADD INDEX `FK_MALNUTRITIONCONTROL_CREATED_BY_IDX` (`MLN_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_malnutritioncontrol` 
ADD CONSTRAINT `FK_MALNUTRITIONCONTROL_CREATED_BY`
  FOREIGN KEY (`MLN_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_medicaldsr` 
ADD INDEX `FK_MEDICALDSR_CREATED_BY_IDX` (`MDSR_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_medicaldsr` 
ADD CONSTRAINT `FK_MEDICALDSR_CREATED_BY`
  FOREIGN KEY (`MDSR_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_medicaldsrlot` 
ADD INDEX `FK_MEDICALDSRLOT_CREATED_BY_IDX` (`LT_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_medicaldsrlot` 
ADD CONSTRAINT `FK_MEDICALDSRLOT_CREATED_BY`
  FOREIGN KEY (`LT_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_medicaldsrstockmov` 
ADD INDEX `FK_MEDICALDSRSTOCKMOV_CREATED_BY_IDX` (`MMV_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_medicaldsrstockmov` 
ADD CONSTRAINT `FK_MEDICALDSRSTOCKMOV_CREATED_BY`
  FOREIGN KEY (`MMV_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_medicaldsrstockmovtype` 
ADD INDEX `FK_MEDICALDSRSTOCKMOVTYPE_CREATED_BY_IDX` (`MMVT_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_medicaldsrstockmovtype` 
ADD CONSTRAINT `FK_MEDICALDSRSTOCKMOVTYPE_CREATED_BY`
  FOREIGN KEY (`MMVT_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_medicaldsrstockmovward` 
ADD INDEX `FK_MEDICALDSRSTOCKMOVWARD_CREATED_BY_IDX` (`MMVN_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_medicaldsrstockmovward` 
ADD CONSTRAINT `FK_MEDICALDSRSTOCKMOVWARD_CREATED_BY`
  FOREIGN KEY (`MMVN_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_medicaldsrtype` 
ADD INDEX `FK_MEDICALDSRTYPE_CREATED_BY_IDX` (`MDSRT_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_medicaldsrtype` 
ADD CONSTRAINT `FK_MEDICALDSRTYPE_CREATED_BY`
  FOREIGN KEY (`MDSRT_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_medicaldsrward` 
ADD INDEX `FK_MEDICALDSRWARD_CREATED_BY_IDX` (`MDSRWRD_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_medicaldsrward` 
ADD CONSTRAINT `FK_MEDICALDSRWARD_CREATED_BY`
  FOREIGN KEY (`MDSRWRD_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_opd` 
ADD INDEX `FK_OPD_CREATED_BY_IDX` (`OPD_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_opd` 
ADD CONSTRAINT `FK_OPD_CREATED_BY`
  FOREIGN KEY (`OPD_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_operation` 
ADD INDEX `FK_OPERATION_CREATED_BY_IDX` (`OPE_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_operation` 
ADD CONSTRAINT `FK_OPERATION_CREATED_BY`
  FOREIGN KEY (`OPE_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_operationrow` 
ADD INDEX `FK_OPERATIONROW_CREATED_BY_IDX` (`OPER_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_operationrow` 
ADD CONSTRAINT `FK_OPERATIONROW_CREATED_BY`
  FOREIGN KEY (`OPER_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_operationtype` 
ADD INDEX `FK_OPERATIONTYPE_CREATED_BY_IDX` (`OCL_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_operationtype` 
ADD CONSTRAINT `FK_OPERATIONTYPE_CREATED_BY`
  FOREIGN KEY (`OCL_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_patient` 
ADD INDEX `FK_PATIENT_CREATED_BY_IDX` (`PAT_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_patient` 
ADD CONSTRAINT `FK_PATIENT_CREATED_BY`
  FOREIGN KEY (`PAT_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_patientexamination` 
ADD INDEX `FK_PATIENTEXAMINATION_CREATED_BY_IDX` (`PEX_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_patientexamination` 
ADD CONSTRAINT `FK_PATIENTEXAMINATION_CREATED_BY`
  FOREIGN KEY (`PEX_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_patienthistory` 
ADD INDEX `FK_PATIENTHISTORY_CREATED_BY_IDX` (`PAH_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_patienthistory` 
ADD CONSTRAINT `FK_PATIENTHISTORY_CREATED_BY`
  FOREIGN KEY (`PAH_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_patientvaccine` 
ADD INDEX `FK_PATIENTVACCINE_CREATED_BY_IDX` (`PAV_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_patientvaccine` 
ADD CONSTRAINT `FK_PATIENTVACCINE_CREATED_BY`
  FOREIGN KEY (`PAV_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_permissions` 
ADD INDEX `FK_PERMISSIONS_CREATED_BY_IDX` (`P_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_permissions` 
ADD CONSTRAINT `FK_PERMISSIONS_CREATED_BY`
  FOREIGN KEY (`P_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_pregnanttreatmenttype` 
ADD INDEX `FK_PREGNANTTREATMENTTYPE_CREATED_BY_IDX` (`PTT_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_pregnanttreatmenttype` 
ADD CONSTRAINT `FK_PREGNANTTREATMENTTYPE_CREATED_BY`
  FOREIGN KEY (`PTT_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_pricelists` 
ADD INDEX `FK_PRICELISTS_CREATED_BY_IDX` (`LST_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_pricelists` 
ADD CONSTRAINT `FK_PRICELISTS_CREATED_BY`
  FOREIGN KEY (`LST_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_prices` 
ADD INDEX `FK_PRICES_CREATED_BY_IDX` (`PRC_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_prices` 
ADD CONSTRAINT `FK_PRICES_CREATED_BY`
  FOREIGN KEY (`PRC_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_pricesothers` 
ADD INDEX `FK_PRICESOTHERS_CREATED_BY_IDX` (`OTH_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_pricesothers` 
ADD CONSTRAINT `FK_PRICESOTHERS_CREATED_BY`
  FOREIGN KEY (`OTH_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_session_audit` 
ADD INDEX `FK_SESSION_AUDIT_CREATED_BY_IDX` (`SEA_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_session_audit` 
ADD CONSTRAINT `FK_SESSION_AUDIT_CREATED_BY`
  FOREIGN KEY (`SEA_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_supplier` 
ADD INDEX `FK_SUPPLIER_CREATED_BY_IDX` (`SUP_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_supplier` 
ADD CONSTRAINT `FK_SUPPLIER_CREATED_BY`
  FOREIGN KEY (`SUP_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_therapies` 
ADD INDEX `FK_THERAPIES_CREATED_BY_IDX` (`THR_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_therapies` 
ADD CONSTRAINT `FK_THERAPIES_CREATED_BY`
  FOREIGN KEY (`THR_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_user` 
ADD INDEX `FK_USER_CREATED_BY_IDX` (`US_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_user` 
ADD CONSTRAINT `FK_USER_CREATED_BY`
  FOREIGN KEY (`US_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_usergroup` 
ADD INDEX `FK_USERGROUP_CREATED_BY_IDX` (`UG_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_usergroup` 
ADD CONSTRAINT `FK_USERGROUP_CREATED_BY`
  FOREIGN KEY (`UG_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_vaccine` 
ADD INDEX `FK_VACCINE_CREATED_BY_IDX` (`VAC_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_vaccine` 
ADD CONSTRAINT `FK_VACCINE_CREATED_BY`
  FOREIGN KEY (`VAC_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_vaccinetype` 
ADD INDEX `FK_VACCINETYPE_CREATED_BY_IDX` (`VACT_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_vaccinetype` 
ADD CONSTRAINT `FK_VACCINETYPE_CREATED_BY`
  FOREIGN KEY (`VACT_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_visits` 
ADD INDEX `FK_VISITS_CREATED_BY_IDX` (`VST_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_visits` 
ADD CONSTRAINT `FK_VISITS_CREATED_BY`
  FOREIGN KEY (`VST_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `oh_ward` 
ADD INDEX `FK_WARD_CREATED_BY_IDX` (`WRD_CREATED_BY` ASC) VISIBLE;

ALTER TABLE `oh_ward` 
ADD CONSTRAINT `FK_WARD_CREATED_BY`
  FOREIGN KEY (`WRD_CREATED_BY`)
  REFERENCES `oh_user` (`US_ID_A`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;