CREATE TABLE OH_USER_SETTINGS(
 USS_ID INT(11) NOT NULL AUTO_INCREMENT, 
 USS_US_ID_A varchar(50) NOT NULL, 
 USS_CONFIG_NAME varchar(50) NOT NULL,  
 USS_CONFIG_VALUE TEXT NOT NULL,
 PRIMARY KEY (USS_ID),
 FOREIGN KEY (USS_US_ID_A) REFERENCES OH_USER(US_ID_A) ON DELETE CASCADE,
 UNIQUE (USS_US_ID_A)
) ENGINE = INNODB DEFAULT CHARACTER SET utf8;
