
ALTER TABLE OH_ADMISSION
ADD COLUMN ADM_REFERRING_CENTER VARCHAR(255) NULL AFTER ADM_NEXT_APPOINTMENT,
ADD COLUMN ADM_REFERRAL_ALERT VARCHAR(255) NULL AFTER ADM_REFERRING_CENTER,
ADD COLUMN ADM_TRANSPORTATION_MODE VARCHAR(100) NULL AFTER ADM_REFERRAL_ALERT,
ADD COLUMN ADM_REFERRAL_REASON TEXT NULL AFTER ADM_TRANSPORTATION_MODE,
ADD COLUMN ADM_DIAGNOSIS TEXT NULL AFTER ADM_REFERRAL_REASON,
ADD COLUMN ADM_TREATMENT_RECEIVED TEXT NULL AFTER ADM_DIAGNOSIS,
ADD COLUMN ADM_OUTCOME VARCHAR(255) NULL AFTER ADM_TREATMENT_RECEIVED,
ADD COLUMN ADM_IMPROVEMENT_FEEDBACK TEXT NULL AFTER ADM_OUTCOME;
