ALTER TABLE OH_ADMISSION
ADD COLUMN ADM_ALERT_RECEIVED TINYINT(1) AFTER ADM_PRG_DATE_ABORT,
ADD COLUMN ADM_REFERENCE_SHEET TINYINT(1) AFTER ADM_ALERT_RECEIVED,
ADD COLUMN ADM_QUALIFIED_AGENT TINYINT(1) AFTER ADM_REFERENCE_SHEET,
ADD COLUMN ADM_PHYSICAL_EXAM LONGTEXT AFTER ADM_QUALIFIED_AGENT,
ADD COLUMN ADM_TRANSPORTATION VARCHAR(50) AFTER ADM_PHYSICAL_EXAM;