ALTER TABLE OH_USER_SETTINGS DROP FOREIGN KEY oh_user_settings_ibfk_1;
ALTER TABLE OH_USER_SETTINGS DROP INDEX USS_US_ID_A;
ALTER TABLE OH_USER_SETTINGS
ADD CONSTRAINT USS_US_ID_A_FK FOREIGN KEY (USS_US_ID_A) REFERENCES OH_USER(US_ID_A) ON DELETE CASCADE;
ALTER TABLE OH_USER_SETTINGS ADD CONSTRAINT USS_US_ID_A_CONFIG_NAME_IDX UNIQUE (USS_US_ID_A, USS_CONFIG_NAME);
