ALTER TABLE OH_OPERATION MODIFY COLUMN OPE_FOR VARCHAR(20);

UPDATE OH_OPERATION
    SET OPE_FOR='opd_admission' WHERE OPE_FOR='1';
UPDATE OH_OPERATION
    SET OPE_FOR='admission' WHERE OPE_FOR='2';
UPDATE OH_OPERATION
    SET OPE_FOR='opd' WHERE OPE_FOR='3';

ALTER TABLE OH_OPERATION
    MODIFY COLUMN OPE_FOR ENUM('opd_admission', 'admission', 'opd') DEFAULT 'opd_admission';