ALTER TABLE OH_PRICES MODIFY COLUMN PRC_PRICE DECIMAL(19,2) NOT NULL;

ALTER TABLE OH_BILLS MODIFY COLUMN BLL_AMOUNT DECIMAL(19,2) DEFAULT NULL;
ALTER TABLE OH_BILLS MODIFY COLUMN BLL_BALANCE DECIMAL(19,2) DEFAULT NULL;

ALTER TABLE OH_BILLITEMS MODIFY COLUMN BLI_ITEM_AMOUNT DECIMAL(19,2) NOT NULL;

ALTER TABLE OH_BILLPAYMENTS MODIFY COLUMN BLP_AMOUNT DECIMAL(19,2) NOT NULL;

ALTER TABLE OH_MEDICALDSRLOT MODIFY COLUMN LT_COST DECIMAL(19,2) NULL;

ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD MODIFY COLUMN MMVN_MDSR_QTY DECIMAL(19,2) NOT NULL;

ALTER TABLE OH_MEDICALDSRWARD MODIFY COLUMN MDSRWRD_OUT_QTI DECIMAL(19,2) NULL DEFAULT 0;
ALTER TABLE OH_MEDICALDSRWARD MODIFY COLUMN MDSRWRD_IN_QTI INT NULL DEFAULT 0;

ALTER TABLE OH_MEDICALDSR MODIFY COLUMN MDSR_MIN_STOCK_QTI INT NOT NULL DEFAULT 0;
ALTER TABLE OH_MEDICALDSR MODIFY COLUMN MDSR_IN_QTI INT NOT NULL DEFAULT 0;
ALTER TABLE OH_MEDICALDSR MODIFY COLUMN MDSR_OUT_QTI INT NOT NULL DEFAULT 0;

ALTER TABLE OH_MEDICALDSRSTOCKMOV MODIFY COLUMN MMV_QTY INT NOT NULL DEFAULT 0;

ALTER TABLE OH_MEDICALDSRSTOCKMOVWARD_LOG MODIFY COLUMN MMVNL_MDSR_QTY DECIMAL(19,2) NOT NULL DEFAULT 0;
